Repository bbopt/nomad, pull requests merged in 2021-04, with the labels that each got.

#21 last updates
  README.txt
  examples/basic/batch/single_obj/CMakeLists.txt
  examples/basic/batch/single_obj/bb.cpp
  examples/basic/batch/single_obj/param.txt
  examples/basic/batch/single_obj/x.txt
  examples/basic/batch/single_obj_parallel/x.txt
  examples/basic/library/single_obj_parallel/CMakeLists.txt
  examples/basic/library/single_obj_parallel/basic_lib.cpp
  src/Algos/MainStep.cpp
Labels: dev_update

#22 Update develop
  bin/nomad
  examples/CMakeLists.txt
  examples/advanced/batch/FixedVariable/CMakeLists.txt
  examples/advanced/batch/FixedVariable/param.txt
  examples/advanced/batch/FixedVariable/param1.txt
  examples/advanced/batch/FixedVariable/param10.txt
  examples/advanced/batch/FixedVariable/param2.txt
  examples/advanced/batch/FixedVariable/param3.txt
  examples/advanced/batch/FixedVariable/uu.cpp
  examples/advanced/library/Restart/restart.cpp
  examples/advanced/library/exampleForCustomHComputation/CMakeLists.txt
  examples/advanced/library/exampleForCustomHComputation/example.cpp
  examples/advanced/library/exampleForCustomHComputation/readme
  examples/basic/batch/example1/param.txt
  examples/basic/batch/example1/param_History.txt
  examples/basic/batch/example1/param_LH.txt
  examples/basic/batch/example1/param_LH_ONLY.txt
  examples/basic/batch/example1/param_NM.txt
  examples/basic/batch/example1/param_QuadSearch.txt
  examples/basic/batch/example1/param_Stats.txt
  examples/basic/batch/example2/param.txt
  examples/basic/batch/example2/param_NM.txt
  examples/basic/batch/example2/param_QuadSearch.txt
  examples/basic/batch/single_obj/param.txt
  examples/basic/library/single_obj_parallel/CMakeLists.txt
  src/Algos/EvcInterface.cpp
  src/Algos/Mads/MadsMegaIteration.cpp
  src/Algos/SgtelibModel/SgtelibModelUpdate.cpp
  src/Eval/BBOutput.cpp
  src/Eval/Eval.cpp
Labels: dev_update

#24 Feature/add doc
  .travis.yml
  doc/user_guide/Makefile
  doc/user_guide/_logo/nomad_logo.jpg
  doc/user_guide/_themes/sphinx_rtd_theme
  doc/user_guide/bin/extractParamInfo.sh
  doc/user_guide/bin/getAllParametersInfo.sh
  doc/user_guide/figs/blackbox.png
  doc/user_guide/figs/example1.png
  doc/user_guide/figs/livre_DFO_AuHa2017.png
  doc/user_guide/figs/mads-algo.png
  doc/user_guide/make.bat
  doc/user_guide/requirements.txt
  doc/user_guide/source/AdvancedFunctionalities.rst
  doc/user_guide/source/Appendix.rst
  doc/user_guide/source/GettingStarted.rst
  doc/user_guide/source/HowToUseNomad.rst
  doc/user_guide/source/Installation.rst
  doc/user_guide/source/Introduction.rst
  doc/user_guide/source/LibraryMode.rst
  doc/user_guide/source/ListOfParameters.rst
  doc/user_guide/source/ReleaseNotes.rst
  doc/user_guide/source/TricksOfTheTrade.rst
  doc/user_guide/source/allParameters.csv
  doc/user_guide/source/conf.py
  doc/user_guide/source/index.rst
Labels: documentation

#25 Modif L. Salomon
  doc/user_guide/source/AdvancedFunctionalities.rst
  doc/user_guide/source/Installation.rst
  doc/user_guide/source/Introduction.rst
  doc/user_guide/source/LibraryMode.rst
  doc/user_guide/source/TricksOfTheTrade.rst
Labels: documentation, fix

#26 Update develop
  examples/advanced/batch/FixedVariable/runFixed.sh
  ext/sgtelib/src/Surrogate.cpp
  ext/sgtelib/src/TrainingSet.cpp
  ext/sgtelib/src/sgtelib_help.cpp
  src/Algos/Mads/PollMethodBase.cpp
  src/Algos/QuadModel/QuadModelAlgo.cpp
Labels: dev_update

#27 Doc: Add nomad test (nomad -v) at the end of installation.
  doc/user_guide/source/Installation.rst
Labels: fix
